#!/usr/bin/env python3
"""Generate core/itemlevel.lua -- the [itemId] = itemLevel lookup.

NOTHING HERE SHIPS. See tools/README.md.

    python3 tools/gen_itemlevel.py --ilvl <ShaguScore/Database.lua> \
        > core/itemlevel.lua

Source: ShaguScore, by shagu -- https://github.com/shagu/ShaguScore
See tools/README.md for the provenance note. The input is NOT vendored here;
pass it on the command line.

Only ilvl 0 entries are dropped: those are Blizzard/Turtle development stubs
("Kazgrim Test Druid Chest 1") with no real level. Everything with a level is
kept, INCLUDING levels above 65 that the disenchant rule cannot use -- this
file is a factual item-level lookup, not a disenchant-band lookup, and
trimming it to what one consumer happens to need today is the coupling that
bites later. It also lets a caller tell "level known, above our data" apart
from "nothing known at all", which are different things to tell a player.
"""

import argparse, re, sys

HEADER = '''-- Aegis: Exchange
-- core/itemlevel.lua
--
-- [itemId] = itemLevel. GENERATED by tools/gen_itemlevel.py -- do not
-- hand-edit; re-run the generator instead.
--
-- WHY THIS FILE EXISTS. 1.12's GetItemInfo returns no item level -- the long
-- note in `util.ItemInfo` explains how that gap shapes this whole addon --
-- and item level is the single input core/disenchant.lua needs. Without a
-- lookup the disenchant rule is correct and permanently silent.
--
-- WHERE THE DATA COMES FROM, and the honest caveat.
--
--   ShaguScore, by shagu -- https://github.com/shagu/ShaguScore
--
-- ShaguScore ships with **no licence**: no LICENSE file, no header, nothing
-- in its README or .toc. Aegis is MIT. Including it here is therefore a
-- judgement the project owner made deliberately, with attribution, rather
-- than something that happened quietly -- see ROADMAP 3k, which parked the
-- decision as the owner's precisely because it is about someone else's work
-- and not a technical question. If shagu would rather it were not here, it
-- comes out and the addon keeps working: the disenchant rule degrades to
-- what the player has learned by disenchanting things themselves.
--
-- WHAT IT IS AND IS NOT. It is vanilla-era data with a useful but partial
-- slice of Turtle's custom items -- roughly a third of them, and shagu is
-- under no obligation to keep up with Turtle's patches. An absent entry is a
-- clean "I do not know": `de.ItemLevel` returns nil and every caller above it
-- says nothing rather than guessing. Learning item levels from the player's
-- own disenchants is the source that outranks this one, because it is
-- evidence from the server they are actually playing on.
--
-- Levels above 65 are kept even though the disenchant ladder stops there.
-- This is an item-level lookup, not a disenchant-band lookup, and knowing
-- that something is item level 70 is different from knowing nothing about it.

local A = AegisExchange

'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ilvl", required=True, help="ShaguScore Database.lua")
    ap.add_argument("--per-line", type=int, default=10)
    args = ap.parse_args()

    with open(args.ilvl, encoding="utf-8", errors="replace") as fh:
        text = fh.read()

    data, dropped = {}, 0
    for m in re.finditer(r"\[(\d+)\]=(\d+)", text):
        iid, lvl = int(m.group(1)), int(m.group(2))
        if lvl < 1:
            dropped += 1
            continue
        data[iid] = lvl
    if not data:
        sys.stderr.write("no entries parsed -- is that really ShaguScore's "
                         "Database.lua?\n")
        return 1

    ids = sorted(data)
    sys.stdout.write(HEADER)
    print("-- %d items, item levels %d-%d. %d development stubs (item level 0)"
          % (len(ids), data[min(ids, key=lambda i: data[i])],
             data[max(ids, key=lambda i: data[i])], dropped))
    print("-- were dropped.")
    print("A.ilvlData = {")
    for start in range(0, len(ids), args.per_line):
        chunk = ids[start:start + args.per_line]
        print("    " + "".join("[%d]=%d," % (i, data[i]) for i in chunk))
    print("}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
